[package]
name = "hedgehog"
version = "0.2.0"
authors = ["Ryan James Spencer <spencer.ryanjames@gmail.com>"]

[dependencies]
num = "0.2"
num-traits = "0.2"
num-derive = "0.3"
rand = "0.7"
rand_core = "0.5"

[profile.release]
debug = true
