[package]
name = "hedgehog"
version = "0.1.0"
authors = ["Ryan James Spencer <spencer.ryanjames@gmail.com>"]

[dependencies]
num = "0.2"
num-traits = "0.2"
num-derive = "0.2"
rand = "0.6"
rand_core = "0.4"
